version: '3.8'

services:
  php-env:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 9000:80
    depends_on:
      - mysql_db
    networks:
      - app-network

  mysql_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_bimbelonline
      MYSQL_USER: mec
      MYSQL_PASSWORD: root
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5 # Tingkatkan retries untuk menunggu MySQL siap

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports: 
      - 9001:80
    environment:
      PMA_HOST: mysql_db # Host sesuai dengan nama service MySQL
      PMA_USER: mec      # User yang didefinisikan dalam MySQL
      PMA_PASSWORD: root # Password yang sesuai
      PMA_PORT: 3306     # Port default MySQL
    depends_on:         # Tambahkan depends_on untuk memastikan MySQL aktif
      - mysql_db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
