---
- name: Deploy PHP Native Application
  hosts: web_servers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PHP and required extensions
      apt:
        name:
          - php
          - php-cli
          - php-fpm
          - php-mysql
          - php-curl
          - php-xml
        state: present

    - name: Ensure web server is installed (Apache in this case)
      apt:
        name: apache2
        state: present

    - name: Ensure Apache service is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy PHP application to the web server
      copy:
        src: /path/to/local/php-app/
        dest: /var/www/html/

    - name: Set permissions for PHP files
      file:
        path: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes
