---
- name: Install and configure MySQL
  hosts: all
  become: yes
  tasks:
    - name: Install MySQL package
      apt:
        name: mysql-server
        state: present

    - name: Start and enable MySQL service
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Secure MySQL installation
      shell: |
        mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY 'your_root_password';"
        mysql -e "DELETE FROM mysql.user WHERE User='';"
        mysql -e "DROP DATABASE IF EXISTS test;"
        mysql -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';"
        mysql -e "FLUSH PRIVILEGES;"
      args:
        executable: /bin/bash

    - name: Create a database
      mysql_db:
        name: mydatabase
        state: present

    - name: Create a database user
      mysql_user:
        name: myuser
        password: 'mypassword'
        priv: 'mydatabase.*:ALL'
        host: "%"
        state: present
